/*
	Sales Prediction

	The East Coast sales division of a company generates 58 percent of total sales.
	Based on that percentage, write a program that will predict how much the East Coast
	division will generate if the company has $8.6 million in sales this year.
*/

/*
	pseudocode

	initatialize a variable for east cost sales divison at .58
	initialize a variable for the company profit of 8.6 million (8.6e6)
	initalize the prediction variable
	multiply the company profit x the sales division to get the prediction
	display the results
*/

#include <iostream> //preprocessor to use cout
using namespace std;

int main () //main program
{
	double eastCoastSales = 0.58, //to set the variable at 58% for the sales generated by the division
		companyProfit = 8.6e6,    // to set the variable at 8.6 million
		prediction;				  // to save the prediction

	prediction = companyProfit * eastCoastSales; //to determine the annual prediction

	cout << "East Coast Sales Division annual prediciton for the year is " << prediction<< endl;

}