/*
Doug Wheeldon
CISS 241
Programming I
*/
/*
		Rock, Paper,Scissors,Lizard,Spock

In this assignment, you will create the game called Rock Paper Scissors game with a little twist to it. In this version, you will also include Lizard and Spock. 
This means the players have the choice of Rock, Paper, Scissors, Lizard, and Spock.

The program will play the game between a user and the computer. The game will continue until there is a winner to the game, 
the user should not be prompted to see if they want to continue when there is a tie in the game. If the game is a tie then the program must make the user play again, until there is a winner.
Once there is a winner, the program (game) must end.

The computers choice will be a random number generated by the program using the random number generator. The number must be limited to the following values:

Rock
Paper
Scissors
Lizard
Spock
Use a menu to prompt the user for their choice, using the same values as above. The program will then display the computer’s choice and the user’s choice in a textual format. 
Meaning if the computer random number is 3 then it should display something like “The computer choice is Scissors”.

The program will then determine if there is a winner or a tie. If there is a winner the program must tell the user, the rule the winner won by (listed below).

A winner is determined using the following rules:

Scissors cut paper
Paper covers rock
Rock crushes lizard
Lizard poisons Spock
Spock smashes (or melts) scissors
Scissors decapitate lizard
Lizard eats paper
Paper disproves Spock
Spock vaporizes rock
Rock breaks scissors
The program must be divided into functions with at least the following functions:

int getUserChoice()
	Displays a menu of choices
	Prompts the user for their choice from the menu
	Return the users choice as an integer to main
int getComputerChoice()
	Use the random number generator to create the computer's choice
	returns the computer's choice as an integer to main
bool determineWinner(int userChoice, int compChoice)
	Uses the two parameters to determine if there is a winner based on the rules provided above.
	Return true if there is a winner, false otherwise (used to determine if tie so that the game can continue in main).
	If a winner, then the correct message must be display indicating who won and by what rule.
void displayChoice(int choice)
	To be used display user choice.
	To be used to display computer choice.
	Should be called two times o Display the choice as text not numeric (Such as “Rock” for choice of 1).
	The program must indicate whose choice it is. Does not need to be done in the function
	Function just displays the choice, a single word.

*/
/*
		pseudocode
	initialize constant global variables 1 - 5 for the choice options
	function prototypes
	main program()
	do while no winner	
		callget computer choice ()
		call displaychoice ()
		call getuserchoice()
		call displaychoice()
	If winner display you won
	else display you lost
	getcomputerchoice()
		get time
		seed ran generator
		get random number between 1 and 5
		return random choice
	getuserchoice()
		display menu options
		ask user to enter an option
		validate it is an appropriate selection
		 if not ask to enter again
		return choice
	determine winner function
	displaychoice
		case switch statements to determine what was selected and display
		
*/
#include <iostream>
#include <ctime>
#include <cstdlib>

using namespace std;

//const variables for the choices
const int rock = 1, paper = 2, scissors = 3, lizard = 4, spock = 5;
bool someoneWins = true;		//bool variable set to true

//function prototypes
int getUserChoice();
int getComputerChoice();
bool determineWinner(int, int);
void displayChoice(int);

int main()
{
	
	int userChoice, compChoice;		//variables to store choices
	

	do
	{
		userChoice = getUserChoice();	//calls userchoie meny and returns to userChoice
		displayChoice(userChoice);	//calls displaychoice and displays selection
		compChoice = getComputerChoice();	//calls getcomputerchoice returns random choice to compChoice
		displayChoice(compChoice);	//displays compchoice
		someoneWins = determineWinner(userChoice, compChoice);	//calls determine winner function
	} while (someoneWins != true);

	//end the program
	cout << "Thank you for playing." << endl;
	return 0;
		
}


/*************************************************************************
*	get user choice function                                             *
*   displays a menu and gets the user choice                             *
*	Validates the answer then returns as int                             *
**************************************************************************/

int getUserChoice()
{
	int choice;
	//menu
	cout << "\t\tRock, Paper, Scissors, Lizard, Spock\n\n"; //
	cout << "1. Rock\n2. Paper\n3. Scissors\n4. Lizard\n5. Spock\n\n" << endl;
	cout << "Make Your Choice: ";
	cin >> choice;
	while (choice < 1 || choice > 5)		//validate entry 
	{
		cout << "Invalid Choice." << endl;
		cout << "Make your Choice: ";
		cin >> choice;
	}
	return choice;
}

/*************************************************************************
*	get comp Choice function											 *
*	uses a random number generator to get a random number				 *
*   from 1 to 5 then returns value as int                                *
**************************************************************************/

int getComputerChoice()
{
	int MIN = 1, MAX = 5, ran_numb; //variables for min and max numbers for generator
	
	//get system time
	unsigned seed = time(0);
	
	//seed random number generator
	srand(seed);

	//generate random number
	ran_numb = (rand() % (MAX - MIN + 1)) + MIN;

	return ran_numb;
}

/**************************************************************************
*			Display Choice Function										  *
* accepts an int argument and displays as text based on what              *
* was selected                                                            *
***************************************************************************/

void displayChoice(int Choice)
{
	//cout <<"Test for choice # " << Choice << endl;
	switch (Choice)
	{
	case 1: 
		cout << "Rock" << endl;
		break;
	case 2: 
		cout << "Paper" << endl;
		break;
	case 3: 
		cout << "Scissors" << endl;
		break;
	case 4: 
		cout << "Lizard" << endl;
		break;
	case 5: 
		cout << "Spock" << endl;
		break;
	}
}

/*************************************************************************
*          determine winner function                                     * 
*  accepts int x 2 arguments for comp and user choice                    *
*  determines winner and returns a bool to main                          *
*                                                                        *
**************************************************************************/

bool determineWinner(int user, int comp)
{
	if (comp == 1)		//rock computer choice; if else if statements for user choice and victory conditions.  
	{
		if (user == 1)
		{
			cout << " Computer Chooses Rock and Player Choose Rock" << endl;
			cout << "No Winner" << endl;
			cout << "Tie Game" << endl;
			someoneWins = false;
		}
		else if (user == 2)
		{
			cout << "Computer Chooses Rock and Player Chooses Paper" << endl;
			cout << "Paper Covers Rock" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 3)
		{
			cout << "Computer Chooses Rock and Player Chooses Scissors" << endl;
			cout << "Rock smashes Scissors" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 4)
		{
			cout << "Computer Chooses Rock and Player Chooses Lizard" << endl;
			cout << "Rock Crushes Lizards head" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
		else if (user == 5)
		{
			cout << "Computer Chooses Rock and Player Chooses Spock" << endl;
			cout << "Spock Vaporizes Rock" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
	}
	if (comp == 2)			//paper computer choice; if else if statements for user choice and victory conditions
	{
		if (user == 1)
		{
			cout << "Player Chooses Rock and Computer Chooses Paper" << endl;
			cout << "Paper Covers Rock" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
		else if (user == 2)
		{
			cout << "Player Chooses Paper and Computer Chooses Paper" << endl;
			cout << "No winner" << endl;
			cout << "Tie Game" << endl;
			someoneWins = false;
		}
		else if (user == 3)
		{
			cout << "Computer Chooses Paper and Player Chooses Scissors" << endl;
			cout << "Scissors cuts Paper" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 4)
		{
			cout << "Computer Chooses Paper and Player Chooses Lizard" << endl;
			cout << "Lizard eats Paper" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 5)
		{
			cout << "Computer Chooses Paper and Player Chooses Spock" << endl;
			cout << "Paper disproves Spock" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
	}
	if (comp == 3)			//scissors computer choice; if else if statements for user choice and victory conditions
	{
		if (user == 1)
		{
			cout << "Player Chooses Rock and Computer Chooses Scissors" << endl;
			cout << "Rock smashes Scissors" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 2)
		{
			cout << "Computer Chooses Scissors and Player Chooses Paper" << endl;
			cout << "Scissors cuts Paper " << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
		else if (user == 3)
		{
			cout << "Computer Chooses Scissors and Player Chooses Scissors" << endl;
			cout << "No Winner" << endl;
			cout << "Tie Game" << endl;
			someoneWins = false;
		}
		else if (user == 4)
		{
			cout << "Computer Chooses Scissors and Player Chooses Lizard" << endl;
			cout << "Scissors cuts Lizards head off" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
		else if (user == 5)
		{
			cout << "Computer Chooses Scissors and Player Chooses Spock" << endl;
			cout << "Spock Melts Scissors" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
	}
	if (comp == 4)			//Lizard Computer choice; if else if statments for user choice and victory conditions
	{
		if (user == 1)
		{
			cout << "Player Chooses Rock and Computer Chooses Lizard" << endl;
			cout << "Rock crushes Lizards Head" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 2)
		{
			cout << "Computer Chooses Lizard and Player Chooses Paper" << endl;
			cout << "Lizard eats Paper" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
		else if (user == 3)
		{
			cout << "Computer Chooses Lizard and Player Chooses Scissors" << endl;
			cout << "Scissors cuts Liards head off" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 4)
		{
			cout << "Computer Chooses Lizard and Player Chooses Lizard" << endl;
			cout << "No Winner" << endl;
			cout << "Tie Game" << endl;
			someoneWins = false;
		}
		else if (user == 5)
		{
			cout << "Computer Chooses Lizard and Player Chooses Spock" << endl;
			cout << "Lizard Poisons Spock" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
	}
	if (comp == 5)			//spock computer choice; if else if statements for user choice and victory conditions
	{
		if (user == 1)
		{
			cout << "Player Chooses Rock and Computer Chooses Spock" << endl;
			cout << "Spock vaporizes Rock" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
		else if (user == 2)
		{
			cout << "Computer Chooses Spock and Player Chooses Paper" << endl;
			cout << "Paper disproves Spock" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 3)
		{
			cout << "Computer Chooses Spock and Player Chooses Scissors" << endl;
			cout << "Spock smashes Scissors" << endl;
			cout << "Computer Wins" << endl;
			someoneWins = true;
		}
		else if (user == 4)
		{
			cout << "Computer Chooses Spock and Player Chooses Lizard" << endl;
			cout << "Lizard poisons Spock" << endl;
			cout << "Player Wins" << endl;
			someoneWins = true;
		}
		else if (user == 5)
		{
			cout << "Computer Chooses Spock and Player Chooses Spock" << endl;
			cout << "No Winner" << endl;
			cout << "Tie Game" << endl;
			someoneWins = false;
		}
	}
	return someoneWins;
}